# Generated by Django 4.2.7 on 2023-11-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("image", models.ImageField(upload_to="")),
                ("release_date", models.DateField()),
                ("lte_exists", models.BooleanField()),
            ],
        ),
    ]
