# Generated by Django 4.2.7 on 2023-11-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0004_phone_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
        migrations.AlterField(
            model_name="phone",
            name="slug",
            field=models.SlugField(),
        ),
    ]
